spring:
  application:
    name: student-reactive
  datasource:
    initialize: true

  r2dbc:
    initialization-mode: always
    driver-class-name: org.h2.Driver
    url: r2dbc:h2:mem://./testdb?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

  h2:
    console:
      enabled: true
      settings:
        trace: true
        web-allow-others: true

logging:
  level:
    org.h2: INFO
    org.springframework: INFO
    org.springframework.r2dbc: INFO